#:schema node_modules/wrangler/config-schema.json
name = "echo-server"
main = "src/index.ts"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

minify = true
logpush = true
workers_dev = false
upload_source_maps = true 

routes = [
    "*.echo.cyberjake.xyz/*"
]

[observability]
enabled = true

